### PR TITLE
Enhancement/596/ wait should return result

### PR DESCRIPTION
**Pull request by svettwer**
Closes#596

### CODE REVIEW

**Comment by cliffle** [comment]
When I try to build the legacy-types I get an error
```
> @sakuli/legacy-types@2.4.0 build /home/cliff/gitprojects/sakuli/packages/sakuli-legacy-types
> ts-node -P tsconfig.json src/build-dts-file


Using TypeScript 4.1.3 from /home/cliff/gitprojects/sakuli/packages/sakuli-legacy-types/node_modules/typescript/lib
Warning: You are running in an unsupported TypeScript version! TypeDoc supports 3.9.x || 4.0.x
Error: /home/cliff/gitprojects/sakuli/packages/sakuli-legacy/src/context/sahi/action/common-action/common-actions.function.ts(60)
 Type 'WaitReturn' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
```

**Comment by svettwer** [comment]
:thinking: Would you mind to check whether this is related to your local setup? because several builds in CI/CD passen without any issue.

**Comment by svettwer** [comment]
Ah, okay, I see. This error is not a build breaker

**Comment by svettwer** [comment]
It seems this error is a little older, when we updated to typescript 4.1.3

**Comment by svettwer** [comment]
Extracted the typedoc issue to https://github.com/sakuli/sakuli/issues/610 as it does not relate to this PR.

**Review by cliffle — COMMENTED** [review]
LGTM :+1: Only found a little type :joy:

**Review by cliffle — APPROVED** [review]

**Pull request merged**
