### PR TITLE
(#422) Applied prettier

### PR DESCRIPTION
**Pull request by svettwer**
Hiho :wave: 

Now as I think about it, we should start a new code period in sonar after the merge. Otherwise our quality gate will fail forever.

What do you think?

### CODE REVIEW

**Comment by cliffle** [comment]
I agree that we should start a new code period. :+1: 

It looks like the pipeline is broken because the `@ts-ignore` in `create-masterkey-command.class.spec.ts` isn't on the right line.

**Comment by svettwer** [comment]
I'll have a look. If this is the case: Good that the code formatting is breaking the syntax. :+1:

**Comment by svettwer** [comment]
I just realize that this is not a syntax issue, now that I read your comment correctly. Sorry was a little bit too early for me obviously. :joy:

**Comment by svettwer** [comment]
Okay, the issue lays in the way prettier formats the code. A manual change to the location of `@ts-ignore` was relocated by the commit hook.

**Comment by svettwer** [comment]
I've found various discussion on that topic:

- https://github.com/prettier/prettier/issues/5411
- https://github.com/microsoft/TypeScript/issues/33256

And you can't use `@ts-ignore` on a block: https://github.com/Microsoft/TypeScript/issues/19573

Nevertheless, I like the interpretation of `@ts-ignore` in [this statement](https://github.com/prettier/prettier/issues/5411#issuecomment-567080379) to be an temporary solution as a TODO and therefore should be resolved. I mean... since when has a TODO comment been a temporary solution in the real world, but I think we all get the point. :rofl:

**Comment by svettwer** [comment]
Builds are passing now, quality gate is broken as expected. 
Please review every single line to be sure everything is okay. :joy: :rofl: :crossed_fingers: :stuck_out_tongue_winking_eye:

**Pull request merged**
