### PR TITLE
(#134) add frame retry logic and add it to actions

### PR DESCRIPTION
**Pull request by tnobody**
This PR introduces a generic frame switch in every action defined in [ActionApi](https://sakuli.io/apidoc/sakuli-legacy/interfaces/actionapi.html):
When an element cannot be found in the page, Sakuli will iterate over each available iframe or frame and retries the action in each of them until it succeeds.

Some things that are still not covered:
- Fetching elements using `_fetch` or `_count` will not find elements in within frames, due to some technical limitations around the API-Design (I can explain in more detail if needed). To cover this case we should open a new issue anyway
- Performance is very poor when Elements are nested in frames. This is not directly related to the implementation of the frame handling. It's rather a common issue with timeouts when Sakuli cannot find an element.

### CODE REVIEW

**Comment by ZNicoZ** [comment]
Extreme performance issues, fetching of three elements takes over 100 seconds.
Please first fix the performance issues and after that let´s try with the automatical switch of frames again.

Good: manual setting of frame still works!

**Comment by tnobody** [comment]
> Extreme performance issues, fetching of three elements takes over 100 seconds.
> Please first fix the performance issues and after that let´s try with the automatical switch of frames again.
> 
> Good: manual setting of frame still works!
> 
> Perhaps #251 will solve some of the performance issues for this.

well at least with #251 you are able to decrease the timeout to find an element which will finally trigger to search in a new frame (so overall time should be way smaller)

**Comment by tnobody** [comment]
@cliffle I just run your example and everything worked well (firefoy and chrome) could you provide more details, logs, cli output etc.

**Comment by cliffle** [comment]
You are right, @tnobody. I think i used `npm rebuild` instead of `npm run rebuild` to rebuild Sakuli.

**Comment by tnobody** [comment]
> You are right, @tnobody. I think i used `npm rebuild` instead of `npm run rebuild` to rebuild Sakuli.

Ok, i didn't know that `npm rebuild` is an actual command 🙈

**Pull request merged**
