### PR TITLE
Bugfix/313/invalid session

### PR DESCRIPTION
**Pull request by svettwer**
This PR is based on the changes of #319. I'll rebase the PR in case #319 is merged earlier.

### CODE REVIEW

**Comment by svettwer** [comment]
Hiho! :wave: 

Thx for the review. The duplicate was a good catch! :+1: 
I applied the changes accordingly and removed the Intellij Specific comments.

BR,
Sven

**Comment by svettwer** [comment]
> When I run the tests, I noticed that the following message appears in the output:
> 
> ```
> jest-haste-map: duplicate manual mock found: index
>   The following files share their name; please delete one of them:
>     * <rootDir>/context/__mocks__/index.ts
>     * <rootDir>/context/sahi/__mocks__/index.ts
> ```

Concerning this, I'm not sure where this comes from. I checked the implementation and could not find a duplicated manual mock... :thinking: 
Have you found it?

**Comment by cliffle** [comment]
> > When I run the tests, I noticed that the following message appears in the output:
> > ```
> > jest-haste-map: duplicate manual mock found: index
> >   The following files share their name; please delete one of them:
> >     * <rootDir>/context/__mocks__/index.ts
> >     * <rootDir>/context/sahi/__mocks__/index.ts
> > ```
> 
> Concerning this, I'm not sure where this comes from. I checked the implementation and could not find a duplicated manual mock... 
> Have you found it?

I think it's facebook/jest#2070

**Comment by svettwer** [comment]
Okay, then I'd recommend to ignore it. As the PR in the issue is merged since August 19 it might be fixed when we update jest.

**Pull request merged**
